
/**
 * Group 2
 * Sanjeet Kapadia   2018B4A70137P
 * Lingesh Kumaar    2018B4A70857P
 * Aman Mishra       2018B4A70877P
 * Sidharth Varghese 2019A7PS1133P
 * Edara Bala Mukesh 2019A7PS0081P
 */

#include <stdio.h>

#include "lexer.h"
#include "parser.h"

#define OUTFILE "./stage1exe"

void usageError() {
    printf("Usage error: " OUTFILE " testCase.txt parseTreeOut.txt\n");
    exit(EXIT_FAILURE);
}

int main(int argc, char **argv) {

    if (argc != 3)
        usageError();

    printf("***************** Compiler Stage 1 - Group 2 *****************\n\n");
    printf(GRN "Status:" RESET "\n");
    printf("Both lexical and syntax analyzer modules implemented\n");
    printf("FIRST and FOLLOW sets automated\n");
    printf("Module works with all 6 testcases\n");
    printf("Error handling and recovery implemented\n");
    printf("Parse tree can be constructed\n");

    int choice;
    for (;;) {
        printf(BLU "\n----------------------------------------------------------------------" RESET "\n\n");
        printf("0. Exit\n");
        printf("1. Strip comments and print comment-free code to stdout\n");
        printf("2. Print token list generated by lexer\n");
        printf("3. Parse input testcase file and save parsetree to parsetree out file\n");
        printf("4. Demonstrate time taken by lexer and parser\n");
        printf("Enter choice: ");
        scanf("%d", &choice);

        switch (choice) {

        case 0:
            exit(EXIT_SUCCESS);

        case 1:
            removeComments(argv[1], NULL);
            break;

        case 2:
            runLexerOnInputSourceCode(argv[1]);
            break;

        case 3:
            nary_free(printParseTree(parseInputSourceCode(argv[1]), argv[2]));
            break;

        case 4: {
            clock_t start_time, end_time;
            double  total_CPU_time, total_CPU_time_in_seconds;
            start_time = clock();

            nary_free(printParseTree(parseInputSourceCode(argv[1]), argv[2])); // utilizes the lexer as well

            end_time                  = clock();
            total_CPU_time            = (double)(end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

            printf("\nTotal CPU time            = %f\nTotal CPU time in seconds = %f\n", total_CPU_time,
                   total_CPU_time_in_seconds);
            break;
        }

        default:
            printf(RED "\nInvalid choice" RESET "\n");
        }

        // flush the input buffer, but not with fflush
        char c;
        while ((c = getchar()) != '\n')
            continue;
    }

    return EXIT_SUCCESS;
}
